spring:
  application:
    name: payment-transaction-manager
  config:
    import: optional:dotenv:.env
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: payment_user
    password: payment_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  h2:
    console:
      enabled: true    

stripe:
  api:
    key: ${STRIPE_API_KEY}


